# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kgw < Formula
  desc "Make your OpenAPI definition the source of truth for API resources in cluster"
  homepage "https://kusk.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kgw/releases/download/0.1.0/kgw_0.1.0_macOS_x86_64.tar.gz"
      sha256 "94de337d819cf2afc02ed25d6915053cafedadca3abb933fffdc0406fc6c51e5"

      def install
        bin.install "kgw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/kgw/releases/download/0.1.0/kgw_0.1.0_macOS_arm64.tar.gz"
      sha256 "f1b2cb494beca84af946d3a785b67fa84a150be133f0239645bd7c430075dfe6"

      def install
        bin.install "kgw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kgw/releases/download/0.1.0/kgw_0.1.0_Linux_x86_64.tar.gz"
      sha256 "cd1a9e1ad8776b1f6641d3aaef2729350ea32331f5e30a080313781985598ed9"

      def install
        bin.install "kgw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/kgw/releases/download/0.1.0/kgw_0.1.0_Linux_arm64.tar.gz"
      sha256 "7685ee06b263322fda038663f9aa13e8718449b699622de6077c3725f0ab4dc0"

      def install
        bin.install "kgw"
      end
    end
  end
end
