# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kgw < Formula
  desc "Make your OpenAPI definition the source of truth for API resources in cluster"
  homepage "https://kusk.io"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kgw/releases/download/v0.1.1/kgw_0.1.1_macOS_x86_64.tar.gz"
      sha256 "e06a0a1f872708b9bf7b255dfe85e4306eceef85ca19e579b9f40080d358f01d"

      def install
        bin.install "kgw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/kgw/releases/download/v0.1.1/kgw_0.1.1_macOS_arm64.tar.gz"
      sha256 "aee12362e22fab7777dd4f5d874dfd634b7a37ae1814bf922d36023581fa04c0"

      def install
        bin.install "kgw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/kgw/releases/download/v0.1.1/kgw_0.1.1_Linux_arm64.tar.gz"
      sha256 "0b0c73c957a6362145df1d6f6e164e3e297ca777dbbdc9f057dae6bada38efd7"

      def install
        bin.install "kgw"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kgw/releases/download/v0.1.1/kgw_0.1.1_Linux_x86_64.tar.gz"
      sha256 "3fe8399c07b3b3a509e8f19e72cf222cbd4554dffc0eea645f82fea78f2e5487"

      def install
        bin.install "kgw"
      end
    end
  end
end
