# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubtestTest < Formula
  desc "Make your OpenAPI definition the source of truth for API resources in cluster"
  homepage "https://kusk.io"
  version "0.0.2"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kubtest-test/releases/download/v0.0.2/kubtest-test_0.0.2_macOS_x86_64.tar.gz"
      sha256 "4181d5937a40d5060b96a395962c556957be0c12d6b0596125ee76d672d86373"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/kubtest-test/releases/download/v0.0.2/kubtest-test_0.0.2_macOS_arm64.tar.gz"
      sha256 "b62164755a215d14810ceb324b74f9a921638a53b356852ad7bd74736e20e3a9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kubtest-test/releases/download/v0.0.2/kubtest-test_0.0.2_Linux_x86_64.tar.gz"
      sha256 "d98c49927fdf8fb2525bf82ce28c22b43deab59cbb3f80f2a1d8162ca3d5a7e3"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/kubtest-test/releases/download/v0.0.2/kubtest-test_0.0.2_Linux_arm64.tar.gz"
      sha256 "c0175f2c49029e22797a17b4454d627c9883cc1d994f9d569591cbb27b22fb64"
    end
  end

  def install
    bin.install "kubtest-test"
  end
end
