# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KuskGen < Formula
  desc "Make your OpenAPI definition the source of truth for API resources in cluster"
  homepage "https://kusk.io"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/kusk-gen/releases/download/v0.7.0/kusk-gen_macOS_arm64.tar.gz"
      sha256 "8e0d4afbb7428ee9268e353169ac3075926f3f05f3a1efde92c81458b3bfa4a1"

      def install
        bin.install "kusk-gen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kusk-gen/releases/download/v0.7.0/kusk-gen_macOS_x86_64.tar.gz"
      sha256 "64c1597336d3e6e85cfdfc64ba6c6159e510fa69f1ef45bc76dc5161f18984a3"

      def install
        bin.install "kusk-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kusk-gen/releases/download/v0.7.0/kusk-gen_Linux_x86_64.tar.gz"
      sha256 "b1f1176395737a0db67985d62b42c9fb3b95fe8b43d38e769034705dfb5f4456"

      def install
        bin.install "kusk-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/kusk-gen/releases/download/v0.7.0/kusk-gen_Linux_arm64.tar.gz"
      sha256 "0916241548ce5f268458d5fa82b651074f352306044a96278a7cc35f646929ee"

      def install
        bin.install "kusk-gen"
      end
    end
  end
end
