# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kusk < Formula
  desc "Make your OpenAPI definition the source of truth for API resources in cluster"
  homepage "https://kusk.io"
  version "1.3.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kusk-gateway/releases/download/v1.3.19/kusk_1.3.19_macOS_x86_64.tar.gz"
      sha256 "1051416afe28b1b99647ed8f1ad6c92619a423961094244587da16f61d080c31"

      def install
        bin.install "kusk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubeshop/kusk-gateway/releases/download/v1.3.19/kusk_1.3.19_macOS_arm64.tar.gz"
      sha256 "5390338d4a28de425bd16dd6d28e4d3d48fa0c15b0a90d76ba79473e39dbf185"

      def install
        bin.install "kusk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubeshop/kusk-gateway/releases/download/v1.3.19/kusk_1.3.19_Linux_arm64.tar.gz"
      sha256 "7c2e359f34bbc9afd6796c5fbda4517ce96020d4ba0191a159fcaa451e2b1d7f"

      def install
        bin.install "kusk"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubeshop/kusk-gateway/releases/download/v1.3.19/kusk_1.3.19_Linux_x86_64.tar.gz"
      sha256 "17f4d539c08e360b42bcd1311d8dd2fafe705fd77fbb8f96a20dfe38730b6c06"

      def install
        bin.install "kusk"
      end
    end
  end
end
